import "./globals.css";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { QueryClientProviderWithClient } from "@/context/query-client-provider";
import { AuthUserProvider } from "@/context/auth-user-provider";
import { ModalPetDeailsProvider } from "@/context/modal-pet-details-provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthUserProvider>
          <QueryClientProviderWithClient>
            <ModalPetDeailsProvider>{children}</ModalPetDeailsProvider>
          </QueryClientProviderWithClient>
        </AuthUserProvider>
      </body>
    </html>
  );
}
